apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  namespace: nginx
  labels:
    app: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react-app
          image: altamsh/notepad-frontend-appm
          ports:
            - containerPort: 3000
